Enabled extravolumes for both Keda and Metrics server deployment
kedacore/charts pull request #114
Opened 2020-12-27 21:40 UTC by HansK-p

Enabled addition of extra volume mounts for both the Keda and the Metrics server deployment. This is needed if there is a need to run Metrics server with a read only root file system, hopefully there are other use cases where this can be useful too.

Ref #113

2021-01-04 15:36 UTC, zroubalik approved these changes
LGTM, just minor comment on the version

2021-01-04 15:36 UTC, zroubalik commented on keda/Chart.yaml
> +version: 2.0.2
Not sure whether we want to increase the version as part of this PR

2021-01-28 07:40 UTC, tomkerkhove commented
@HansK-p Any update on this?

2021-01-28 19:08 UTC, HansK-p commented
Sorry. I didn't catch that I should make any changes. I'll decrease the version. The failing check is covered by another PR (if I remember correctly).

2021-01-29 07:05 UTC, tomkerkhove requested changes
LGTM, just need to:
- Document these new values in the README of the chart
- Fix DCO

2021-04-21 18:30 UTC, t3mi commented
@HansK-p can you finish this PR please? Or if you don't mind I can do that for you.

2021-04-21 19:33 UTC, HansK-p commented
I'm sorry I haven't done a follow-up. I most certainly don't mind if you do it @t3mi

2021-08-25 12:17 UTC, tomkerkhove commented
Done in #146 - Thanks anyway @HansK-p !

2021-08-25 12:17 UTC, closed without merging