aggregate rbac for crds to default roles
kedacore/charts pull request #257
Opened 2022-03-23 08:59 UTC by TheKangaroo

this change adds ClusterRoles to aggregate rbac for
clustertriggerauthentications, scaledjobs, scaledobjects and
triggerauthentications to the kubernetes default roles view, edit and
admin via aggregation.
These ClusterRoles are optional and disabled by default. Set
rbac.aggregateToDefaultRoles to enable.

Signed-off-by: Till Adam <lxmail@web.de>

### Checklist

- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] README is updated with new configuration values *(if applicable)*

Fixes #256

2022-04-09 21:33 UTC, JorTurFer requested changes
LGTM!
Thanks for this improvement! 
Only one small nit

2022-04-09 21:33 UTC, JorTurFer commented on keda/Chart.yaml
> +version: 2.6.3
Please, revert this change because we bump the version during the chart release

2022-04-09 21:33 UTC, JorTurFer commented
@kedacore/keda-helm-contributors

2022-04-11 05:41 UTC, TheKangaroo commented
Ah thank you @JorTurFer, I reverted the version change.

2022-04-11 13:40 UTC, tomkerkhove approved these changes
LGTM, but be careful. We depend on what KEDA core generates as well so we might want to do it there as well.

2022-04-11 14:42 UTC, TheKangaroo commented
@tomkerkhove I'm not sure how keda core and helm chart plays together here, but if a PR in keda core is necessary, could you point me to the right direction?

2022-04-13 11:38 UTC, tomkerkhove commented
KEDA core generates YALM files to deploy but let's ask @zroubalik if this can be included first or if we should maintain it seperately

2022-04-13 12:38 UTC, zroubalik commented
Yeah, this should be changed in the core first. rbac is generated with kubebuilder from annotation on controllers, for example here: https://github.com/kedacore/keda/blob/9dbde78e238591870018a4eb9e2425b412ad26eb/controllers/keda/scaledobject_controller.go#L55-L63

2022-07-11 05:08 UTC, tomkerkhove commented
Are you up for contributing this in KEDA core as well @TheKangaroo?

2022-07-11 06:41 UTC, TheKangaroo commented
@tomkerkhove, sorry, this got lost on my side.
I had a look at @zroubalik's example and the kubebuilder docs, but I'm not sure how I can add aggregation roles via marker comments (i.e. add 'rbac.authorization.k8s.io/aggregate-to-xxxxx: "true"' labels to the generated clusterroles).

Or is ist just a matter of adding these clusterroles without any aggreation or bindings to the kedacore code? In this case, wouldn't it be better to drop the use of aggreation in this PR as well and just create clusterroles and clusterrolebindings instead?
Sorry if these are silly questions, I never worked with kubebuilder before.

2022-07-11 06:47 UTC, tomkerkhove commented
I will leave that up to @zroubalik to help though!

No worries, we are here to help you!

2022-09-24 20:23 UTC, JorTurFer approved these changes

2022-09-24 20:44 UTC, JorTurFer commented
We should give some attention to this @kedacore/keda-helm-contributors

2022-09-26 15:54 UTC, TheKangaroo commented
I had a brief chat with @zroubalik via slack about the kubebuilder part, but we didn't manage to find time to do this yet.
We can give this another shot if one of you can help me with some hints on how to do this.

2023-01-06 09:24 UTC, JorTurFer commented
We are waiting because kubebuiler doesn't support this and we generate the rbac files using it, but considering that the changes are in metadata section, I guess that can make then here for helm only. Wdyt @zroubalik @TheKangaroo ?

2023-01-09 09:12 UTC, TheKangaroo commented
I just rebased the PR.
We switched to the AKS managed keda in the meantime, so we do not use this chart anymore, but I still think this is useful for others as well.

2023-05-15 14:05 UTC, u0078867 commented
Any news? Also interested here ...

2023-05-17 12:41 UTC, zroubalik commented
> As this is a role on top of other roles for giving access to KEDA resources as part of other cluster existing roles, I'd merge it without any change in core. @tomkerkhove @zroubalik ?

agree!

2023-05-17 12:41 UTC, zroubalik approved these changes
LGTM, thanks for the contribution!

2023-05-17 12:42 UTC, merged