Apiservice port from values
kedacore/charts pull request #452
Opened 2023-05-23 20:04 UTC by hyperbolist

_Provide a description of what has been changed_

### Checklist

- [X] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [ ] README is updated with new configuration values *(if applicable)*
- [X] A PR is opened to update KEDA core ([repo](https://github.com/kedacore/keda)) *(if applicable, ie. when deployment manifests are modified)*

### Fixes

- `APIService` now takes its `port` from `service.portHttps`.  Previously, the APIService's port was omitted in the manifest, which resulted in the port defaulting to 443, even if we actually set the port to something else via service.portHttps.  When this happens, you'll see its availability check as false with reason `ServicePortError` and a message complaining that the APIService is not available on the port specified in its manifest.

2023-05-26 17:32 UTC, JorTurFer requested changes
nice catch with the APIService!
as we don't release all the changes on each commit, could you undo the other changes? (keeping only the change in the APIService manifest)

2023-05-27 20:40 UTC, hyperbolist commented
> as we don't release all the changes on each commit, could you undo the other changes?

Of course, reverted.

2023-05-27 21:19 UTC, JorTurFer approved these changes

2023-05-27 21:20 UTC, JorTurFer commented
Thanks for the improvement! :heart:

2023-05-27 21:20 UTC, merged