support "none" as identity provider
kedacore/charts pull request #618
Opened 2024-03-12 10:56 UTC by roee-hersh

identity provider: "none" is officially supported and allowed value based on the docs and keda golang structs:

https://github.com/kedacore/keda/blob/main/apis/keda/v1alpha1/triggerauthentication_types.go#L123
```
const (
	PodIdentityProviderNone          PodIdentityProvider = "none"
	PodIdentityProviderAzure         PodIdentityProvider = "azure"
	PodIdentityProviderAzureWorkload PodIdentityProvider = "azure-workload"
	PodIdentityProviderGCP           PodIdentityProvider = "gcp"
	PodIdentityProviderAwsEKS        PodIdentityProvider = "aws-eks"
	PodIdentityProviderAwsKiam       PodIdentityProvider = "aws-kiam"
	PodIdentityProviderAws           PodIdentityProvider = "aws"
)
```

and in the docs:
https://keda.sh/docs/2.13/concepts/authentication/

```
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {trigger-authentication-name}
  namespace: default # must be same namespace as the ScaledObject
spec:
  podIdentity:
      provider: none | azure | azure-workload | aws | aws-eks | aws-kiam | gcp  # Optional. Default: none
...
```

yet it is missing since crds refactor

### Checklist

- [x] I have verified that my change is according to the [deprecations & breaking changes policy](https://github.com/kedacore/governance/blob/main/DEPRECATIONS.md)
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-signing-your-work))
- [x] README is updated with new configuration values *(if applicable)* [learn more](https://github.com/kedacore/charts/blob/main/CONTRIBUTING.md#documentation)
- [x] A PR is opened to update KEDA core ([repo](https://github.com/kedacore/keda)) *(if applicable, ie. when deployment manifests are modified)*

2024-03-12 13:07 UTC, JorTurFer commented
Nice catch!
Although you just keep it unset, it's also true that `none` should be accepted based on docs. I've opened a PR into KEDA code to reflect this change too: https://github.com/kedacore/keda/pull/5593

2024-03-12 14:37 UTC, tomkerkhove approved these changes

2024-03-12 20:56 UTC, JorTurFer requested changes
We need to include this change in multiple places (in the same places as the [core PR](https://github.com/kedacore/keda/pull/5593/files)), could you update all of them? 🙏

2024-03-15 23:19 UTC, JorTurFer commented
Thanks for your contribution! :heart:

2024-03-15 23:20 UTC, JorTurFer approved these changes

2024-03-15 23:20 UTC, merged