Adding the ability to set the default HTTP timeout
kedacore/charts pull request #90
Opened 2020-10-26 21:53 UTC by arschles

https://github.com/kedacore/keda/pull/1251 adds a new environment variable to allow users to set the default HTTP timeout in the system. This exposes that setting in the helm chart.

2020-10-26 21:56 UTC, arschles commented
The failure in https://github.com/kedacore/charts/pull/90/checks?check_run_id=1311498573 is this: 

```shell
Error:  templates/21-metrics-clusterrolebinding.yaml: object name does not conform to Kubernetes naming requirements: "keda-operator:system:auth-delegator": invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253
```

I didn't touch that file so I think it's unrelated to my change, but I'm happy to fix it if you like.

2020-10-27 06:17 UTC, tomkerkhove commented
> The failure in [#90 (checks)](https://github.com/kedacore/charts/pull/90/checks?check_run_id=1311498573) is this:
> 
> ```shell
> Error:  templates/21-metrics-clusterrolebinding.yaml: object name does not conform to Kubernetes naming requirements: "keda-operator:system:auth-delegator": invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253
> ```
> 
> I didn't touch that file so I think it's unrelated to my change, but I'm happy to fix it if you like.

This is ok, you can ignore that one.

2020-10-27 06:18 UTC, tomkerkhove requested changes
LGTM, but can you update the README as well please?

2020-10-27 06:19 UTC, tomkerkhove commented
Will hold off until the PR gets merged as well.

2020-11-13 22:19 UTC, arschles commented
@tomkerkhove sorry for the delay. I made this update in conjunction with https://github.com/kedacore/keda/pull/1251. I'm not sure what order they should be merged, but please let me know if you'd like help with it.

2020-11-16 09:20 UTC, tomkerkhove approved these changes
LGTM with a suggestion, but waiting with merging until PR gets merged

2020-11-16 09:20 UTC, tomkerkhove commented on keda/values.yaml
> +httpTimeout: 3000
Maybe a nit but what if we use `http.timeout` here to align with the other conventions?

```suggestion
http:
  timeout: 3000
```

2021-01-28 07:40 UTC, tomkerkhove commented
Any update on this @arschles ?

2021-03-18 09:28 UTC, zroubalik commented
@arschles could you update this pls?

2021-03-29 23:18 UTC, arschles commented
forgot about this one, sorry folks! I'll update this tomorrow first thing

2021-03-30 17:09 UTC, arschles commented
@tomkerkhove @zroubalik resolved the conflicts and made the `httpTimeout` ==> `http.timeout` change that you requested @tomkerkhove .

Sorry again about the delay. I didn't save this repository in my notifications presets - since fixed!

2021-03-30 17:16 UTC, tomkerkhove approved these changes
LGTM

2021-03-30 17:16 UTC, tomkerkhove commented
Thanks @arschles!

2021-03-30 17:17 UTC, tomkerkhove commented
Can you fix the deploy issue please?

2021-03-30 22:41 UTC, arschles commented
@tomkerkhove my bad - fixed and merging now.

2021-03-31 08:46 UTC, tomkerkhove commented
Thank you!

2021-03-31 08:46 UTC, merged